In [1]:
import numpy as np


In [9]:
np1=np.array([3,4,5,56])

In [10]:
np1

array([ 3,  4,  5, 56])

In [16]:
mat1=np.array([[1,5,6,6,7,7], [3,5,6,6,7,7]])

In [17]:
mat1

array([[1, 5, 6, 6, 7, 7],
       [3, 5, 6, 6, 7, 7]])

In [18]:
rang= np.arange(0,10,2)

In [19]:
rang

array([0, 2, 4, 6, 8])

In [20]:
mat2=np.linspace(0,10,20)

In [21]:
mat2

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])