In [1]:
import numpy as np


In [9]:
np1=np.array([3,4,5,56])

In [10]:
np1

array([ 3,  4,  5, 56])

In [16]:
mat1=np.array([[1,5,6,6,7,7], [3,5,6,6,7,7]])

In [17]:
mat1

array([[1, 5, 6, 6, 7, 7],
       [3, 5, 6, 6, 7, 7]])

In [18]:
rang= np.arange(0,10,2)

In [19]:
rang

array([0, 2, 4, 6, 8])

In [20]:
mat2=np.linspace(0,10,20)

In [21]:
mat2

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [28]:
mat3= np.random.rand(20,4)

In [29]:
mat3

array([[0.73571775, 0.59237923, 0.72948483, 0.02893745],
       [0.26414884, 0.19117068, 0.34761778, 0.80666351],
       [0.18208064, 0.13762799, 0.38255226, 0.92612463],
       [0.78337091, 0.87811381, 0.15087189, 0.9085165 ],
       [0.32034886, 0.92480227, 0.12112331, 0.47162494],
       [0.79958798, 0.52850397, 0.34827946, 0.84417127],
       [0.70577976, 0.23310141, 0.64705943, 0.18575597],
       [0.63652599, 0.67174217, 0.1252331 , 0.50496701],
       [0.29591819, 0.13355181, 0.53349422, 0.36203995],
       [0.1451998 , 0.95932801, 0.36159457, 0.58488982],
       [0.22040279, 0.80329689, 0.14221273, 0.42166975],
       [0.19231454, 0.13841437, 0.13485949, 0.07953805],
       [0.16320884, 0.22727115, 0.98896457, 0.99459886],
       [0.73965738, 0.78049062, 0.47056001, 0.22956225],
       [0.59387502, 0.59833739, 0.71824816, 0.53129904],
       [0.6366776 , 0.51886799, 0.72158231, 0.70612844],
       [0.3237102 , 0.70003142, 0.36514181, 0.45781941],
       [0.57969915, 0.9527883 ,