In [1]:
import numpy as np


In [9]:
np1=np.array([3,4,5,56])

In [10]:
np1

array([ 3,  4,  5, 56])

In [16]:
mat1=np.array([[1,5,6,6,7,7], [3,5,6,6,7,7]])

In [17]:
mat1

array([[1, 5, 6, 6, 7, 7],
       [3, 5, 6, 6, 7, 7]])

In [18]:
rang= np.arange(0,10,2)

In [19]:
rang

array([0, 2, 4, 6, 8])